using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;
using VitaMj.Config.Editor;

/// <summary>
/// 扫描 <c>Assets/Config</c> 下全部 <c>.xlsx</c>：同一工作簿内**不区分 Sheet**，格式一致即合并为一表；
/// 第 1 行为字段关键字（首列须为 tag），第 2 行为类型，第 3 行起为数据。
/// **可无数据行**（仅表头），此时导出空 JSON（根对象为「无键」），仍可生成 Row 类并注册 Bootstrap。
/// 表名 = 文件名（净化后）；无需再手写注册代码。
/// </summary>
public static class ExportAllConfigs
{
    const string ConfigFolder = "Assets/Config";
    const string GeneratedFolder = "Assets/Scripts/Config/Generated";
    const string ExportResourcesFolder = "Assets/Resources/ExportConfig";
    const string BootstrapFile = "Assets/Scripts/Config/Generated/ConfigTableBootstrap.g.cs";

    [MenuItem("VitaMJ/配置表/导出全部 (.xlsx)", priority = 10)]
    public static void ExportFromMenu()
    {
        ExportAll(false);
    }

    public static void ExportAll(bool silent)
    {
        if (!Directory.Exists(ConfigFolder))
            Directory.CreateDirectory(ConfigFolder);

        Directory.CreateDirectory(GeneratedFolder);
        Directory.CreateDirectory(ExportResourcesFolder);

        var bootLines = new List<string>();
        var generatedRowFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        string[] xlsxFiles = Directory.GetFiles(ConfigFolder, "*.xlsx", SearchOption.TopDirectoryOnly)
            .Where(f => !Path.GetFileName(f).StartsWith("~"))
            .ToArray();

        int exportedWorkbooks = 0;

        foreach (string path in xlsxFiles)
        {
            string bookStem = SanitizeKey(Path.GetFileNameWithoutExtension(path));
            if (!TryMergeWorkbook(path, bookStem, silent, out string tableKey, out string className, out string rowCs,
                    out byte[] bin))
                continue;

            exportedWorkbooks++;

            string rowPath = Path.Combine(GeneratedFolder, className + ".g.cs");
            File.WriteAllText(rowPath, rowCs, new UTF8Encoding(true));
            generatedRowFiles.Add(className + ".g.cs");

            string binPath = Path.Combine(ExportResourcesFolder, tableKey + ".bytes");
            File.WriteAllBytes(binPath, bin);

            bootLines.Add(
                $"            ConfigReader.RegisterTable<{className}>(\"{tableKey}\");");

            if (!silent)
                Debug.Log($"[Config] 导出 {tableKey}（合并全部 Sheet）→ {binPath}");
        }

        WriteBootstrap(bootLines);
        PruneOrphanGeneratedRows(generatedRowFiles);
        AssetDatabase.Refresh();

        if (!silent)
            Debug.Log($"[Config] 导出完成：{exportedWorkbooks}/{xlsxFiles.Length} 个工作簿已写入 Generated 与 Resources/ExportConfig（含 Bootstrap 注册）。");
    }

    static void PruneOrphanGeneratedRows(HashSet<string> keepFiles)
    {
        if (!Directory.Exists(GeneratedFolder))
            return;

        foreach (string file in Directory.GetFiles(GeneratedFolder, "*ConfigRow.g.cs", SearchOption.TopDirectoryOnly))
        {
            string name = Path.GetFileName(file);
            if (name.Equals("ConfigTableBootstrap.g.cs", StringComparison.OrdinalIgnoreCase))
                continue;
            if (!keepFiles.Contains(name))
            {
                File.Delete(file);
                if (File.Exists(file + ".meta"))
                    File.Delete(file + ".meta");
            }
        }
    }

    static void WriteBootstrap(List<string> lines)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("namespace VitaMj.Config");
        sb.AppendLine("{");
        sb.AppendLine("    static class ConfigTableBootstrap");
        sb.AppendLine("    {");
        sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]");
        sb.AppendLine("        static void RegisterAllTables()");
        sb.AppendLine("        {");
        sb.AppendLine("            ConfigReader.ClearRegistry();");

        foreach (string line in lines.OrderBy(x => x, StringComparer.Ordinal))
            sb.AppendLine(line);

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(BootstrapFile, sb.ToString(), new UTF8Encoding(true));
    }

    /// <summary>
    /// 合并同一 xlsx 内所有 Sheet：首张有效表定义列结构，其余表第 1、2 行须一致。
    /// </summary>
    static bool TryMergeWorkbook(string path, string bookStem, bool silent, out string tableKey, out string className,
        out string rowCs, out byte[] bin)
    {
        tableKey = bookStem;
        className = $"{bookStem}ConfigRow";
        rowCs = null;
        bin = null;

        List<ConfigXlsxBookReader.SheetData> sheets = ConfigXlsxBookReader.ReadAllSheets(path);
        if (sheets == null || sheets.Count == 0)
            return false;

        List<(int col, string kw, string prop, string jsonKey, string clr)> keywords = null;
        var root = new JObject();

        foreach (ConfigXlsxBookReader.SheetData sheet in sheets)
        {
            if (sheet.Rows.Count == 0)
                continue;

            if (!TryGetRowCells(sheet, 1, out Dictionary<int, string> headerCells) ||
                !TryGetRowCells(sheet, 2, out Dictionary<int, string> typeCells))
            {
                if (!silent)
                    Debug.LogWarning($"[Config] [{bookStem}] 跳过工作表「{sheet.Name}」：缺少第 1、2 行表头。");
                continue;
            }

            if (keywords == null)
            {
                if (!TryBuildKeywords(headerCells, typeCells, bookStem, out keywords))
                    return false;
            }
            else if (!SchemasMatch(headerCells, typeCells, keywords, sheet.Name, bookStem))
            {
                Debug.LogError($"[Config] [{bookStem}] 工作表「{sheet.Name}」与首张表的字段/类型不一致，已中止导出。");
                return false;
            }

            AppendSheetDataRows(sheet, keywords, root, bookStem, sheet.Name, silent);
        }

        if (keywords == null)
        {
            if (!silent)
                Debug.LogWarning($"[Config] [{bookStem}] 无任何有效 Sheet（需至少一行表头）。");
            return false;
        }

        // 允许仅含第 1、2 行（字段 + 类型）而无数据行：照样生成 Row 类、空 JSON「{}」与 VMJ1 二进制，
        // 新增表后不必先填数据才能通过一键导出；后续在 Excel 第 3 行起填写即可。
        if (root.Count == 0 && !silent)
            Debug.Log($"[Config] [{bookStem}] 当前无数据行，已导出空表（{{}}）；从第 3 行起填写 tag 与数据行即可。");

        string json = root.ToString(Formatting.None);
        bin = EncodeBinary(json);
        rowCs = GenerateRowClass(className, keywords);
        return true;
    }

    static bool TryBuildKeywords(
        Dictionary<int, string> headerCells,
        Dictionary<int, string> typeCells,
        string bookStem,
        out List<(int col, string kw, string prop, string jsonKey, string clr)> keywords)
    {
        keywords = null;

        int maxCol = Math.Max(headerCells.Keys.DefaultIfEmpty(-1).Max(), typeCells.Keys.DefaultIfEmpty(-1).Max());
        if (maxCol < 0)
            return false;

        keywords = new List<(int col, string kw, string prop, string jsonKey, string clr)>();
        string tagKeywordNorm = null;

        for (int c = 0; c <= maxCol; c++)
        {
            headerCells.TryGetValue(c, out string kwRaw);
            typeCells.TryGetValue(c, out string typRaw);

            string kw = (kwRaw ?? string.Empty).Trim();
            string typ = (typRaw ?? string.Empty).Trim();
            if (string.IsNullOrEmpty(kw))
                continue;

            if (keywords.Count == 0 && !kw.Equals("tag", StringComparison.OrdinalIgnoreCase))
            {
                Debug.LogError($"[Config] 「{bookStem}」第一列关键字必须为 tag，当前为「{kw}」。");
                keywords = null;
                return false;
            }

            if (keywords.Count == 0)
                tagKeywordNorm = kw;

            string jsonKey = kw;
            string prop = SanitizeIdentifier(kw);
            string clr = MapClrType(typ);

            keywords.Add((c, kw, prop, jsonKey, clr));
        }

        if (keywords.Count == 0 || tagKeywordNorm == null)
        {
            keywords = null;
            return false;
        }

        if (keywords[0].col != 0)
        {
            Debug.LogError($"[Config] 「{bookStem}」tag 必须位于第一列（Excel A 列）。");
            keywords = null;
            return false;
        }

        return true;
    }

    static bool SchemasMatch(
        Dictionary<int, string> headerCells,
        Dictionary<int, string> typeCells,
        List<(int col, string kw, string prop, string jsonKey, string clr)> firstKeywords,
        string sheetName,
        string bookStem)
    {
        if (!TryBuildKeywords(headerCells, typeCells, bookStem, out List<(int col, string kw, string prop, string jsonKey, string clr)> candidate))
            return false;

        if (candidate.Count != firstKeywords.Count)
        {
            Debug.LogError($"[Config] [{bookStem}] Sheet「{sheetName}」列数与首张表不一致：{candidate.Count} vs {firstKeywords.Count}。");
            return false;
        }

        for (int i = 0; i < firstKeywords.Count; i++)
        {
            var a = firstKeywords[i];
            var b = candidate[i];
            if (a.col != b.col ||
                !string.Equals(a.kw, b.kw, StringComparison.Ordinal) ||
                !string.Equals(a.clr, b.clr, StringComparison.Ordinal))
            {
                Debug.LogError($"[Config] [{bookStem}] Sheet「{sheetName}」第 {i + 1} 列与首张表不一致（列索引或关键字或类型）。");
                return false;
            }
        }

        return true;
    }

    static void AppendSheetDataRows(
        ConfigXlsxBookReader.SheetData sheet,
        List<(int col, string kw, string prop, string jsonKey, string clr)> keywords,
        JObject root,
        string bookStem,
        string sheetName,
        bool silent)
    {
        int tagCol = keywords[0].col;

        foreach (int rowNum in sheet.Rows.Keys)
        {
            if (rowNum < 3)
                continue;

            if (!sheet.Rows.TryGetValue(rowNum, out Dictionary<int, string> cells))
                continue;

            var rowObj = new JObject();
            string tagVal = null;

            foreach (var (col, kw, prop, jsonKey, clr) in keywords)
            {
                cells.TryGetValue(col, out string cellText);
                cellText = cellText ?? string.Empty;
                cellText = cellText.Trim();

                if (!TryParseCell(cellText, clr, out JToken token))
                    token = clr == "string" ? new JValue(cellText) : JValue.CreateNull();

                rowObj[jsonKey] = token;

                if (col == tagCol)
                    tagVal = cellText;
            }

            if (string.IsNullOrEmpty(tagVal))
                continue;

            if (root.ContainsKey(tagVal))
            {
                if (!silent)
                    Debug.LogWarning($"[Config] [{bookStem}] tag「{tagVal}」在 Sheet「{sheetName}」重复定义，后写覆盖（合并规则）。");
            }

            root[tagVal] = rowObj;
        }
    }

    static string GenerateRowClass(string className, List<(int col, string kw, string prop, string jsonKey, string clr)> keywords)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Newtonsoft.Json;");
        sb.AppendLine();
        sb.AppendLine("namespace VitaMj.Config");
        sb.AppendLine("{");
        sb.AppendLine($"    [System.Serializable]");
        sb.AppendLine($"    public sealed class {className}");
        sb.AppendLine("    {");

        foreach (var (_, _, prop, jsonKey, clr) in keywords)
        {
            string csharpType = clr switch
            {
                "string" => "string",
                "int" => "int",
                "long" => "long",
                "float" => "float",
                "double" => "double",
                "bool" => "bool",
                _ => "string"
            };

            sb.AppendLine($"        [JsonProperty(\"{EscapeString(jsonKey)}\")]");
            sb.AppendLine($"        public {csharpType} {prop} {{ get; set; }}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    static byte[] EncodeBinary(string json)
    {
        byte[] utf8 = Encoding.UTF8.GetBytes(json);
        var ms = new MemoryStream(8 + utf8.Length);
        ms.WriteByte((byte)'V');
        ms.WriteByte((byte)'M');
        ms.WriteByte((byte)'J');
        ms.WriteByte((byte)'1');
        byte[] len = BitConverter.GetBytes(utf8.Length);
        ms.Write(len, 0, 4);
        ms.Write(utf8, 0, utf8.Length);
        return ms.ToArray();
    }

    static bool TryGetRowCells(ConfigXlsxBookReader.SheetData sheet, int row1Based, out Dictionary<int, string> cells)
    {
        return sheet.Rows.TryGetValue(row1Based, out cells);
    }

    static string MapClrType(string typRaw)
    {
        if (string.IsNullOrWhiteSpace(typRaw))
            return "string";

        string t = typRaw.Trim().ToLowerInvariant();
        return t switch
        {
            "string" or "str" or "text" => "string",
            "int" or "int32" => "int",
            "long" or "int64" => "long",
            "float" or "single" => "float",
            "double" => "double",
            "bool" or "boolean" => "bool",
            _ => "string"
        };
    }

    static bool TryParseCell(string text, string clr, out JToken token)
    {
        token = null;
        if (clr == "string")
        {
            token = new JValue(text ?? string.Empty);
            return true;
        }

        if (string.IsNullOrWhiteSpace(text))
        {
            token = clr switch
            {
                "int" => new JValue(0),
                "long" => new JValue(0L),
                "float" => new JValue(0f),
                "double" => new JValue(0d),
                "bool" => new JValue(false),
                _ => new JValue("")
            };
            return true;
        }

        try
        {
            switch (clr)
            {
                case "int":
                    if (double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out double di))
                        token = new JValue((int)Math.Round(di));
                    else if (int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out int ii))
                        token = new JValue(ii);
                    else
                        return false;
                    return true;
                case "long":
                    if (long.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out long ll))
                        token = new JValue(ll);
                    else if (double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out double dl))
                        token = new JValue((long)Math.Round(dl));
                    else
                        return false;
                    return true;
                case "float":
                    if (float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out float ff))
                        token = new JValue(ff);
                    else
                        return false;
                    return true;
                case "double":
                    if (double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out double dd))
                        token = new JValue(dd);
                    else
                        return false;
                    return true;
                case "bool":
                    string low = text.Trim().ToLowerInvariant();
                    if (low is "1" or "true" or "yes" or "y")
                        token = new JValue(true);
                    else if (low is "0" or "false" or "no" or "n")
                        token = new JValue(false);
                    else
                        return false;
                    return true;
            }
        }
        catch
        {
            return false;
        }

        return false;
    }

    /// <summary>用于文件名与 tableKey。</summary>
    static string SanitizeKey(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "Sheet";

        var sb = new StringBuilder(name.Length);
        foreach (char ch in name)
        {
            if (char.IsLetterOrDigit(ch))
                sb.Append(ch);
            else
                sb.Append('_');
        }

        string s = sb.ToString().Trim('_');
        return string.IsNullOrEmpty(s) ? "Sheet" : s;
    }

    /// <summary>C# 属性名。</summary>
    static string SanitizeIdentifier(string name)
    {
        name = name.Trim();
        if (string.IsNullOrEmpty(name))
            return "_col";

        var sb = new StringBuilder();
        foreach (char ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');
        }

        string id = sb.ToString();
        if (char.IsDigit(id[0]))
            id = "_" + id;

        return id;
    }
}
